# Generated by Django 2.1.3 on 2018-11-22 17:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioInferior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('script', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioLateral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('script', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioSuperior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('script', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Explicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('documento', models.FileField(upload_to='', verbose_name='Uploaded pdf')),
                ('dateTimeUp', models.DateTimeField(auto_now=True)),
                ('proceso', models.TextField(blank=True, choices=[('B', 'B'), ('T', 'T'), ('TB', 'TB')])),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IpsFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_conexion', models.DateField(auto_now=True)),
                ('ip', models.CharField(max_length=50)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_routeable', models.BooleanField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr_api.File')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
