# Generated by Django 2.2.1 on 2019-05-21 21:58

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('documento', models.FileField(upload_to='', verbose_name='Uploaded pdf')),
                ('dateTimeUp', models.DateTimeField(auto_now=True)),
                ('proceso', models.TextField(blank=True, choices=[('B', 'B'), ('T', 'T'), ('TB', 'TB')])),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinSizeDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='defecto', max_length=255)),
                ('tam_min', models.PositiveIntegerField(default=40000)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Traza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funcion_llamada', models.CharField(blank=True, max_length=255)),
                ('datos_in', django.contrib.postgres.fields.jsonb.JSONField()),
                ('datos_out', django.contrib.postgres.fields.jsonb.JSONField()),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('error', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IpsFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_conexion', models.DateField(auto_now=True)),
                ('ip', models.CharField(max_length=50)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_routeable', models.NullBooleanField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr_api.File')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
