# Generated by Django 2.1.3 on 2019-01-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explicacion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='explicacion',
            name='titulo_imagen',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
