# Generated by Django 2.1.3 on 2019-01-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0002_auto_20190130_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explicacion',
            name='imagen',
            field=models.URLField(blank=True),
        ),
    ]
