# Generated by Django 2.1.3 on 2019-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0003_auto_20190130_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explicacion',
            name='imagen',
            field=models.URLField(),
        ),
    ]
