# Generated by Django 2.1.3 on 2019-01-31 11:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0004_auto_20190131_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncioinferior',
            name='script',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='anunciolateral',
            name='script',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
