# Generated by Django 2.1.3 on 2019-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0005_auto_20190131_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='resuelta',
            field=models.BooleanField(default=False),
        ),
    ]
