# Generated by Django 2.1.3 on 2019-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0006_incidencia_resuelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipsfiles',
            name='is_routeable',
            field=models.NullBooleanField(),
        ),
    ]
