# Generated by Django 2.1.3 on 2019-02-22 19:56

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0007_auto_20190219_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuienSomos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('titulo_imagen', models.CharField(blank=True, max_length=255)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
