# Generated by Django 2.1.3 on 2019-02-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0008_quiensomos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiensomos',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
