# Generated by Django 2.2.1 on 2019-05-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0009_auto_20190222_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnuncioInferior',
        ),
        migrations.DeleteModel(
            name='AnuncioLateral',
        ),
        migrations.DeleteModel(
            name='AnuncioSuperior',
        ),
    ]
