# Generated by Django 2.2.1 on 2019-05-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonousuario',
            name='peticiones_consumidas',
        ),
        migrations.AddField(
            model_name='bonousuario',
            name='peticiones_restantes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
