version: '3'

services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"   # servicos api y admin e localhost:8001 para dejar libre localhost:80 pra angular

    volumes:
      - .:/code
      - ./Extract_refactor/config/nginx:/etc/nginx/conf.d
      - ./Extract_refactor/static:/static
    depends_on:
      - api_web

  dbpostgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ExtractPdf
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  redis:
    image: redis:latest
    hostname: redis
    ports:
     - '6379:6379'


  api_web:
    build: .
    working_dir: /code/Extract_refactor

    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py InitialData && gunicorn Extract_refactor.wsgi -b 0.0.0.0:8000 --timeout 1200000"     #production mode

    #command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn Extract_refactor.wsgi -b 0.0.0.0:8000"     #production mode

    volumes:
      - .:/code
      - ./Extract_refactor/static:/static
    ports:
      - "8000:8000"
    depends_on:
      - dbpostgres
      - redis
      - worker
    links:
      - dbpostgres
      - redis

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code/Extract_refactor
    command: celery worker -A Extract_refactor.celery --loglevel=info
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code/Extract_refactor
    ports:
      - "5555:5555"
    command: celery flower \
      --app= Extract_refactor.celery
      --broker="redis://redis:6379/0"
      --loglevel=info
    links:
      - redis

    depends_on:

      - worker


volumes:
  postgres_data:





