# Generated by Django 2.2.1 on 2019-05-21 21:58

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioInferior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('script', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioLateral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('script', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioSuperior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('script', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('peticiones', models.PositiveIntegerField()),
                ('descripcion', models.TextField(max_length=255)),
                ('precio', models.PositiveIntegerField()),
                ('activado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Explicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('titulo_imagen', models.CharField(blank=True, max_length=255)),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='QuienSomos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('titulo_imagen', models.CharField(blank=True, max_length=255)),
                ('imagen', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
