# Generated by Django 2.2.1 on 2019-05-13 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinSizeDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='defecto', max_length=255)),
                ('tam_min', models.PositiveIntegerField(default=40000)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
    ]
