# Generated by Django 2.2.1 on 2019-05-07 21:57

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioInferior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('script', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioLateral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('script', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioSuperior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('script', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
